local palette = require("palette")

local function set_hl(name, opts)
	vim.api.nvim_set_hl(0, name, opts)
end

local function apply_theme()
	set_hl("Normal", { fg = palette.fg, bg = palette.bg })
	set_hl("NormalNC", { fg = palette.fg, bg = palette.bg })
	set_hl("NormalFloat", { fg = palette.fg, bg = palette.bg_float })
	set_hl("FloatBorder", { fg = palette.purple, bg = palette.bg_float })
	set_hl("EndOfBuffer", { fg = palette.bg, bg = palette.bg })
	set_hl("SignColumn", { bg = palette.bg })
	set_hl("StatusLine", { fg = palette.fg, bg = palette.bg })
	set_hl("StatusLineNC", { fg = palette.fg_muted, bg = palette.bg })
	set_hl("WinSeparator", { fg = palette.bg_highlight, bg = palette.bg })
	set_hl("VertSplit", { fg = palette.bg_highlight, bg = palette.bg })
	set_hl("LineNr", { fg = palette.fg_muted, bg = palette.bg })
	set_hl("CursorLineNr", { fg = palette.purple, bg = palette.bg, bold = true })
	set_hl("Comment", { fg = palette.fg_muted, bg = palette.bg, italic = false })
	set_hl("Visual", { bg = palette.bg_visual })
	set_hl("Pmenu", { fg = palette.fg, bg = palette.bg_float })
	set_hl("PmenuSel", { fg = palette.bg, bg = palette.purple, bold = true })
	set_hl("PmenuSbar", { bg = palette.bg_highlight })
	set_hl("PmenuThumb", { bg = palette.fg_muted })
	set_hl("FoldColumn", { fg = palette.fg_muted, bg = palette.bg })
	set_hl("Folded", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("TelescopeNormal", { fg = palette.fg, bg = palette.bg_float })
	set_hl("TelescopeBorder", { fg = palette.purple, bg = palette.bg_float })
	set_hl("TelescopePromptBorder", { fg = palette.cyan, bg = palette.bg_float })
	set_hl("TelescopePromptTitle", { fg = palette.bg, bg = palette.cyan, bold = true })
	set_hl("TelescopeResultsTitle", { fg = palette.bg, bg = palette.purple, bold = true })
	set_hl("TelescopePreviewTitle", { fg = palette.bg, bg = palette.pink, bold = true })

	set_hl("WinBar", { fg = palette.fg, bg = palette.bg })
	set_hl("WinBarNC", { fg = palette.fg_muted, bg = palette.bg })
	set_hl("DropBarIconUISeparator", { fg = palette.fg_muted, bg = palette.bg })
	set_hl("DropBarCurrentContext", { fg = palette.bg, bg = palette.purple, bold = true })
	set_hl("DropBarMenuCurrentContext", { fg = palette.bg, bg = palette.purple, bold = true })
	set_hl("DropBarMenuFloatBorder", { fg = palette.purple, bg = palette.bg_float })
	set_hl("DropBarMenuNormalFloat", { fg = palette.fg, bg = palette.bg_float })
	set_hl("DropBarMenuHoverEntry", { fg = palette.fg, bg = palette.bg_highlight })
	set_hl("DropBarMenuHoverSymbol", { fg = palette.pink, bg = palette.bg_highlight, bold = true })

	set_hl("BufferLineFill", { bg = palette.bg })
	set_hl("BufferLineBackground", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineTab", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineTabSelected", { fg = palette.fg, bg = palette.bg_selected })
	set_hl("BufferLineTabClose", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineBufferVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineBufferSelected", { fg = palette.fg, bg = palette.bg_selected })
	set_hl("BufferLineNumbers", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineNumbersVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineNumbersSelected", { fg = palette.fg, bg = palette.bg_selected })
	set_hl("BufferLineDuplicate", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineDuplicateVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineDuplicateSelected", { fg = palette.fg, bg = palette.bg_selected })
	set_hl("BufferLinePick", { fg = palette.pink, bg = palette.bg_alt, bold = true })
	set_hl("BufferLinePickVisible", { fg = palette.pink, bg = palette.bg_alt, bold = true })
	set_hl("BufferLinePickSelected", { fg = palette.pink, bg = palette.bg_selected, bold = true })
	set_hl("BufferLineSeparator", { fg = palette.bg, bg = palette.bg_alt })
	set_hl("BufferLineSeparatorVisible", { fg = palette.bg, bg = palette.bg_alt })
	set_hl("BufferLineSeparatorSelected", { fg = palette.bg, bg = palette.bg_selected })
	set_hl("BufferLineIndicatorVisible", { fg = palette.bg_alt, bg = palette.bg_alt })
	set_hl("BufferLineIndicatorSelected", { fg = palette.bg_selected, bg = palette.bg_selected })
	set_hl("BufferLineCloseButton", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineCloseButtonVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineCloseButtonSelected", { fg = palette.fg, bg = palette.bg_selected })
	set_hl("BufferLineModified", { fg = palette.yellow, bg = palette.bg_alt })
	set_hl("BufferLineModifiedVisible", { fg = palette.yellow, bg = palette.bg_alt })
	set_hl("BufferLineModifiedSelected", { fg = palette.yellow, bg = palette.bg_selected })
	set_hl("BufferLineDiagnostic", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineDiagnosticVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineDiagnosticSelected", { fg = palette.cyan, bg = palette.bg_selected })
	set_hl("BufferLineHint", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineHintVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineHintSelected", { fg = palette.green, bg = palette.bg_selected })
	set_hl("BufferLineInfo", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineInfoVisible", { fg = palette.fg_muted, bg = palette.bg_alt })
	set_hl("BufferLineInfoSelected", { fg = palette.cyan, bg = palette.bg_selected })
	set_hl("BufferLineWarning", { fg = palette.yellow, bg = palette.bg_alt, italic = true, bold = true })
	set_hl("BufferLineWarningVisible", { fg = palette.yellow, bg = palette.bg_alt, italic = true, bold = true })
	set_hl("BufferLineWarningSelected", { fg = palette.yellow, bg = palette.bg_selected, italic = true, bold = true })
	set_hl("BufferLineError", { fg = palette.red, bg = palette.bg_alt, italic = true, bold = true })
	set_hl("BufferLineErrorVisible", { fg = palette.red, bg = palette.bg_alt, italic = true, bold = true })
	set_hl("BufferLineErrorSelected", { fg = palette.red, bg = palette.bg_selected, italic = true, bold = true })
end

local group = vim.api.nvim_create_augroup("custom_dracula_palette", { clear = true })
vim.api.nvim_create_autocmd({ "VimEnter", "ColorScheme" }, {
	group = group,
	callback = function()
		vim.schedule(apply_theme)
	end,
})

apply_theme()
